import express, { Application, json, urlencoded } from 'express';
import swaggerUi from 'swagger-ui-express';
import { container } from 'tsyringe';

import { config } from './config/env';
import { errorHandler, notFoundHandler } from './middleware/errorHandler';
import { usePathBase } from './middleware/pathBase';
import { WhatsappService } from './services/whatsappService';

// NOTE: these two imports are GENERATED by tsoa.
// Run `npm run tsoa` (or `npm run build`) before compiling/starting.
//   src/generated/routes.ts     -> RegisterRoutes
//   src/generated/swagger.json  -> OpenAPI spec served at /docs
import { RegisterRoutes } from './generated/routes';
import swaggerDocument from './generated/swagger.json';

/**
 * Builds the Express application: body parsing, Swagger UI, tsoa routes,
 * and error handling. Kept separate from server bootstrap for testability.
 */
export function createApp(): Application {
  const app = express();

  // Strip the ingress sub-path (if any) so all routes below are defined at root.
  app.use(usePathBase(config.pathBase));

  // base64 attachments inside JSON can be large — raise the limit.
  app.use(json({ limit: '25mb' }));
  app.use(urlencoded({ extended: true, limit: '25mb' }));

  // Advertise the public base path so Swagger "Try it out" targets the right URL.
  const spec = config.pathBase
    ? { ...swaggerDocument, servers: [{ url: config.pathBase }] }
    : swaggerDocument;

  // Interactive API docs + raw spec.
  app.use('/docs', swaggerUi.serve, swaggerUi.setup(spec));
  app.get('/openapi.json', (_req, res) => res.json(spec));

  // Login QR as a PNG (only while a QR is pending, i.e. before authentication).
  // Plain route rather than tsoa, since tsoa serializes responses as JSON.
  const whatsapp = container.resolve(WhatsappService);
  app.get('/qr', async (_req, res, next) => {
    try {
      const png = await whatsapp.getQrPng();
      if (!png) {
        res.status(404).json({
          message: `No QR pending (WhatsApp status: ${whatsapp.getStatus()})`,
          code: 'QR_NOT_AVAILABLE',
        });
        return;
      }
      res.setHeader('Content-Type', 'image/png');
      res.setHeader('Cache-Control', 'no-store');
      res.send(png);
    } catch (err) {
      next(err);
    }
  });

  // tsoa-generated routes (wired to controllers via the IoC container).
  RegisterRoutes(app);

  // Fallbacks — order matters: 404 then error handler last.
  app.use(notFoundHandler);
  app.use(errorHandler);

  return app;
}
